apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xz4l18bfk-java-springboot
  janus-idp.io/tekton: xz4l18bfk-java-springboot
  backstage.io/kubernetes-id: xz4l18bfk-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xz4l18bfk-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
